'use strict';
(() => {
  const PRIMARY_RU=[
    'Я недостаточно хорош','Я ничего не стою','Я не творческий человек','Я не могу ничего просить, так как буду отвергнут','Я недостаточно умен','Меня нельзя любить','У меня нет способностей','Я стеснительный человек','Я никому не интересен','Я не идеален','Я слишком стар','Я слишком молод','Я ниже этих людей','Я ленивая/ленив','Я не могу иметь хобби','Я не заслуживаю ничего хорошего','Люди будут судить меня','Я неудачник','Я глупый/глупая','Люди сразу отвергнут меня, как только узнают поближе','Я не красив/красивая','Я слишком толстый/толстая','Я неуклюжий/неуклюжая','Я слишком худой/худая','Я слишком стеснителен/стеснительная','Мое тело не совершенно','Я не привлекательный/привлекательная','Я бессилен/бессильная','Я не важен/важна','Вокруг недобрые люди','Мои желания не имеют никакого значения','Потребности других людей важнее моих','У меня нет силы воли','Если я ослаблю контроль, все плохое выйдет наружу','Люди всегда будут причинять мне боль','Я не доверяю себе','Я не современен/современна','Я никогда не буду соответствовать','Если я буду доверять людям, они сделают мне больно','Никто меня не поддержит и не подбодрит','Я странный/странная','Я примитивный человек','Я плохой/плохая','Я не сексуальный/не сексуальная','Я ущербный/ущербная','Я никогда не повзрослею','Я не имею право быть стройной и красивой','Мои желания и мечты не сбудутся','У меня кризис','Я никто','Мою фигуру не исправить','Я не влияю на свою жизнь','День Рождения лучше не праздновать','Мир мне должен','Легкой жизни не бывает','Учебу не каждый освоит','Мои страхи реальны','Просто так не любят и не дружат','Я не фотогеничен/не фотогенична','Секс не для меня','Я мнительный/мнительная'
  ];
  const DEEP_RU=[
    'Я не заслуживаю любви','Я плохой человек','Я ужасен','Я не заслуживаю уважения','Я неадекватен','Я опозорен','Я не способен любить','Я недостаточно хорош','Я достоин лишь плохих событий','Я не могу быть надежным','Я не могу доверять самому себе','Я не могу доверять моей оценке','Я не могу достичь успеха','Я не контролирую себя','Я бессилен','Я беспомощен','Я слаб','Я не могу защитить себя','Я тупой','Я недостаточно остроумен','Я не имею никакого значения','Я разочарован','Я заслуживаю лишь смерти','Я заслуживаю того, чтобы быть жалким и несчастным человеком','Я не могу получить то, что хочу','Я неудачник (и у меня будут одни неудачи)','Я должен быть безупречным','Я должен всем уделять внимание','Я постоянно болен','Я уродлив (мое тело отвратительно)','Я должен сделать что-то','Я делал что-то плохое','Я в опасности','Я не могу выдержать всё это','Я никому не могу доверять','Я не могу высказать всего этого','Я не заслуживаю...','Я не должен проявлять свои эмоции','Я не могу быть опорой для самого себя','Я не такой, как все','Я должен узнать, как сделать лучше','Я ничего не умею (у меня ничего не получается)'
  ];

  const PRIMARY={
    ru:PRIMARY_RU,
    en:['I am not good enough','I am worthless','I am not a creative person','I cannot ask for anything because I will be rejected','I am not smart enough','I cannot be loved','I have no abilities','I am a shy person','Nobody is interested in me','I am not perfect','I am too old','I am too young','I am beneath these people','I am lazy','I cannot have hobbies','I do not deserve anything good','People will judge me','I am a failure','I am stupid','People will reject me as soon as they get to know me better','I am unattractive','I am too fat','I am clumsy','I am too thin','I am too shy','My body is imperfect','I am not attractive','I am powerless','I am not important','People around me are unkind','My wishes do not matter','Other people’s needs are more important than mine','I have no willpower','If I loosen control, everything bad will come out','People will always hurt me','I do not trust myself','I am not modern enough','I will never measure up','If I trust people, they will hurt me','No one will support or encourage me','I am strange','I am a primitive person','I am bad','I am not sexual','I am defective','I will never grow up','I do not have the right to be slim and beautiful','My wishes and dreams will not come true','I am in crisis','I am nobody','My figure cannot be fixed','I have no influence over my life','It is better not to celebrate my birthday','The world owes me','Life is never easy','Not everyone can handle studying','My fears are real','People do not love or befriend you for no reason','I am not photogenic','Sex is not for me','I am overly suspicious'],
    fr:['Je ne suis pas assez bien','Je ne vaux rien','Je ne suis pas une personne créative','Je ne peux rien demander car je serai rejeté(e)','Je ne suis pas assez intelligent(e)','On ne peut pas m’aimer','Je n’ai aucune capacité','Je suis une personne timide','Je n’intéresse personne','Je ne suis pas parfait(e)','Je suis trop vieux/vieille','Je suis trop jeune','Je suis inférieur(e) à ces gens','Je suis paresseux/paresseuse','Je ne peux pas avoir de loisirs','Je ne mérite rien de bon','Les gens vont me juger','Je suis un échec','Je suis stupide','Les gens me rejetteront dès qu’ils me connaîtront mieux','Je ne suis pas beau/belle','Je suis trop gros/grosse','Je suis maladroit(e)','Je suis trop maigre','Je suis trop timide','Mon corps est imparfait','Je ne suis pas attirant(e)','Je suis impuissant(e)','Je ne suis pas important(e)','Les gens autour de moi sont méchants','Mes désirs n’ont aucune importance','Les besoins des autres sont plus importants que les miens','Je n’ai aucune volonté','Si je relâche le contrôle, tout ce qui est mauvais sortira','Les gens me feront toujours du mal','Je ne me fais pas confiance','Je ne suis pas moderne','Je ne serai jamais à la hauteur','Si je fais confiance aux gens, ils me feront du mal','Personne ne me soutiendra ni ne m’encouragera','Je suis étrange','Je suis une personne primitive','Je suis mauvais(e)','Je ne suis pas sexuel(le)','Je suis défectueux/défectueuse','Je ne grandirai jamais','Je n’ai pas le droit d’être mince et beau/belle','Mes désirs et mes rêves ne se réaliseront pas','Je traverse une crise','Je ne suis personne','Ma silhouette ne peut pas être améliorée','Je n’ai aucune influence sur ma vie','Il vaut mieux ne pas fêter mon anniversaire','Le monde me doit quelque chose','La vie n’est jamais facile','Tout le monde ne peut pas réussir ses études','Mes peurs sont réelles','On ne m’aime pas et on ne devient pas mon ami sans raison','Je ne suis pas photogénique','Le sexe n’est pas pour moi','Je suis excessivement méfiant(e)'],
    de:['Ich bin nicht gut genug','Ich bin nichts wert','Ich bin kein kreativer Mensch','Ich kann um nichts bitten, weil ich abgelehnt werde','Ich bin nicht intelligent genug','Man kann mich nicht lieben','Ich habe keine Fähigkeiten','Ich bin ein schüchterner Mensch','Niemand interessiert sich für mich','Ich bin nicht perfekt','Ich bin zu alt','Ich bin zu jung','Ich stehe unter diesen Menschen','Ich bin faul','Ich darf keine Hobbys haben','Ich verdiene nichts Gutes','Die Leute werden mich verurteilen','Ich bin ein Versager','Ich bin dumm','Die Leute werden mich ablehnen, sobald sie mich besser kennen','Ich bin nicht schön','Ich bin zu dick','Ich bin unbeholfen','Ich bin zu dünn','Ich bin zu schüchtern','Mein Körper ist nicht vollkommen','Ich bin nicht attraktiv','Ich bin machtlos','Ich bin nicht wichtig','Die Menschen um mich herum sind unfreundlich','Meine Wünsche haben keine Bedeutung','Die Bedürfnisse anderer sind wichtiger als meine','Ich habe keine Willenskraft','Wenn ich die Kontrolle lockere, kommt alles Schlechte heraus','Menschen werden mir immer wehtun','Ich vertraue mir selbst nicht','Ich bin nicht modern','Ich werde nie genügen','Wenn ich Menschen vertraue, werden sie mir wehtun','Niemand wird mich unterstützen oder ermutigen','Ich bin seltsam','Ich bin ein primitiver Mensch','Ich bin schlecht','Ich bin nicht sexuell','Mit mir stimmt etwas grundsätzlich nicht','Ich werde nie erwachsen','Ich habe kein Recht, schlank und schön zu sein','Meine Wünsche und Träume werden nicht wahr','Ich bin in einer Krise','Ich bin niemand','Meine Figur lässt sich nicht verbessern','Ich habe keinen Einfluss auf mein Leben','Geburtstage sollte man besser nicht feiern','Die Welt schuldet mir etwas','Ein leichtes Leben gibt es nicht','Nicht jeder schafft eine Ausbildung','Meine Ängste sind real','Man liebt und befreundet sich nicht einfach so','Ich bin nicht fotogen','Sex ist nichts für mich','Ich bin übermäßig misstrauisch'],
    it:['Non sono abbastanza bravo/a','Non valgo nulla','Non sono una persona creativa','Non posso chiedere nulla perché verrò rifiutato/a','Non sono abbastanza intelligente','Non posso essere amato/a','Non ho capacità','Sono una persona timida','Non interesso a nessuno','Non sono perfetto/a','Sono troppo vecchio/a','Sono troppo giovane','Sono inferiore a queste persone','Sono pigro/a','Non posso avere hobby','Non merito nulla di buono','Le persone mi giudicheranno','Sono un fallito/a','Sono stupido/a','Le persone mi rifiuteranno appena mi conosceranno meglio','Non sono bello/a','Sono troppo grasso/a','Sono goffo/a','Sono troppo magro/a','Sono troppo timido/a','Il mio corpo è imperfetto','Non sono attraente','Sono impotente','Non sono importante','Le persone intorno a me sono cattive','I miei desideri non contano','I bisogni degli altri sono più importanti dei miei','Non ho forza di volontà','Se allento il controllo, tutto ciò che è brutto verrà fuori','Le persone mi faranno sempre del male','Non mi fido di me stesso/a','Non sono moderno/a','Non sarò mai all’altezza','Se mi fido delle persone, mi faranno del male','Nessuno mi sosterrà o incoraggerà','Sono strano/a','Sono una persona primitiva','Sono cattivo/a','Non sono sessuale','Sono difettoso/a','Non crescerò mai','Non ho il diritto di essere magro/a e bello/a','I miei desideri e sogni non si realizzeranno','Sono in crisi','Non sono nessuno','La mia figura non può essere migliorata','Non ho alcuna influenza sulla mia vita','È meglio non festeggiare il compleanno','Il mondo mi deve qualcosa','La vita non è mai facile','Non tutti riescono a studiare','Le mie paure sono reali','Le persone non amano e non diventano amiche senza motivo','Non sono fotogenico/a','Il sesso non fa per me','Sono eccessivamente diffidente']
  };

  const DEEP={
    ru:DEEP_RU,
    en:['I do not deserve love','I am a bad person','I am awful','I do not deserve respect','I am inadequate','I am disgraced','I am incapable of loving','I am not good enough','I deserve only bad things','I cannot be reliable','I cannot trust myself','I cannot trust my judgment','I cannot succeed','I cannot control myself','I am powerless','I am helpless','I am weak','I cannot protect myself','I am stupid','I am not clever enough','I do not matter','I am disappointed','I deserve only death','I deserve to be miserable and unhappy','I cannot get what I want','I am a failure (and I will keep failing)','I must be flawless','I must pay attention to everyone','I am constantly ill','I am ugly (my body is disgusting)','I have to do something','I did something bad','I am in danger','I cannot bear all of this','I cannot trust anyone','I cannot say all of this','I do not deserve...','I must not show my emotions','I cannot rely on myself','I am not like everyone else','I must find out how to do better','I cannot do anything (nothing works out for me)'],
    fr:['Je ne mérite pas l’amour','Je suis une mauvaise personne','Je suis horrible','Je ne mérite pas le respect','Je suis inadéquat(e)','Je suis déshonoré(e)','Je suis incapable d’aimer','Je ne suis pas assez bien','Je ne mérite que de mauvaises choses','Je ne peux pas être fiable','Je ne peux pas me faire confiance','Je ne peux pas faire confiance à mon jugement','Je ne peux pas réussir','Je ne me contrôle pas','Je suis impuissant(e)','Je suis sans défense','Je suis faible','Je ne peux pas me protéger','Je suis stupide','Je ne suis pas assez intelligent(e)','Je n’ai aucune importance','Je suis déçu(e)','Je ne mérite que la mort','Je mérite d’être misérable et malheureux(se)','Je ne peux pas obtenir ce que je veux','Je suis un échec (et je continuerai à échouer)','Je dois être irréprochable','Je dois accorder de l’attention à tout le monde','Je suis constamment malade','Je suis laid(e) (mon corps est dégoûtant)','Je dois faire quelque chose','J’ai fait quelque chose de mal','Je suis en danger','Je ne peux pas supporter tout cela','Je ne peux faire confiance à personne','Je ne peux pas dire tout cela','Je ne mérite pas...','Je ne dois pas montrer mes émotions','Je ne peux pas être mon propre soutien','Je ne suis pas comme les autres','Je dois découvrir comment faire mieux','Je ne sais rien faire (rien ne marche pour moi)'],
    de:['Ich verdiene keine Liebe','Ich bin ein schlechter Mensch','Ich bin schrecklich','Ich verdiene keinen Respekt','Ich bin unangemessen','Ich bin entehrt','Ich bin unfähig zu lieben','Ich bin nicht gut genug','Ich verdiene nur schlechte Dinge','Ich kann nicht zuverlässig sein','Ich kann mir selbst nicht vertrauen','Ich kann meinem Urteil nicht vertrauen','Ich kann keinen Erfolg haben','Ich habe mich nicht unter Kontrolle','Ich bin machtlos','Ich bin hilflos','Ich bin schwach','Ich kann mich nicht schützen','Ich bin dumm','Ich bin nicht klug genug','Ich bin bedeutungslos','Ich bin enttäuscht','Ich verdiene nur den Tod','Ich verdiene es, elend und unglücklich zu sein','Ich kann nicht bekommen, was ich will','Ich bin ein Versager (und werde immer wieder scheitern)','Ich muss fehlerlos sein','Ich muss jedem Aufmerksamkeit schenken','Ich bin ständig krank','Ich bin hässlich (mein Körper ist abstoßend)','Ich muss etwas tun','Ich habe etwas Schlechtes getan','Ich bin in Gefahr','Ich kann das alles nicht ertragen','Ich kann niemandem vertrauen','Ich kann das alles nicht aussprechen','Ich verdiene nicht...','Ich darf meine Gefühle nicht zeigen','Ich kann mir selbst keine Stütze sein','Ich bin anders als alle anderen','Ich muss herausfinden, wie es besser geht','Ich kann nichts (mir gelingt nichts)'],
    it:['Non merito amore','Sono una cattiva persona','Sono terribile','Non merito rispetto','Sono inadeguato/a','Sono disonorato/a','Non sono capace di amare','Non sono abbastanza bravo/a','Merito solo cose brutte','Non posso essere affidabile','Non posso fidarmi di me stesso/a','Non posso fidarmi del mio giudizio','Non posso avere successo','Non riesco a controllarmi','Sono impotente','Sono indifeso/a','Sono debole','Non posso proteggermi','Sono stupido/a','Non sono abbastanza intelligente','Non conto nulla','Sono deluso/a','Merito solo la morte','Merito di essere una persona miserabile e infelice','Non posso ottenere ciò che voglio','Sono un fallito/a (e continuerò a fallire)','Devo essere impeccabile','Devo prestare attenzione a tutti','Sono sempre malato/a','Sono brutto/a (il mio corpo è disgustoso)','Devo fare qualcosa','Ho fatto qualcosa di brutto','Sono in pericolo','Non posso sopportare tutto questo','Non posso fidarmi di nessuno','Non posso dire tutto questo','Non merito...','Non devo mostrare le mie emozioni','Non posso essere un sostegno per me stesso/a','Non sono come tutti gli altri','Devo capire come fare meglio','Non so fare nulla (non mi riesce niente)']
  };

  const UI={
    ru:{pTitle:'Первичные ограничивающие убеждения',pSub:'Подсказки из загруженного документа. Нажми на формулировку, чтобы вставить её в редактор.',dTitle:'Убеждение 2 — глубинные убеждения',dSub:'Нажми на формулировку, чтобы вставить её в редактор.',search:'Поиск по убеждениям…',empty:'Ничего не найдено'},
    en:{pTitle:'Primary limiting beliefs',pSub:'Suggestions from the source document. Click a statement to insert it into the editor.',dTitle:'Belief 2 — deep beliefs',dSub:'Click a statement to insert it into the editor.',search:'Search beliefs…',empty:'Nothing found'},
    fr:{pTitle:'Croyances limitantes primaires',pSub:'Suggestions du document source. Cliquez sur une formulation pour l’insérer dans l’éditeur.',dTitle:'Croyance 2 — croyances profondes',dSub:'Cliquez sur une formulation pour l’insérer dans l’éditeur.',search:'Rechercher dans les croyances…',empty:'Aucun résultat'},
    de:{pTitle:'Primäre einschränkende Überzeugungen',pSub:'Hinweise aus dem Quelldokument. Klicke auf eine Formulierung, um sie in den Editor einzufügen.',dTitle:'Überzeugung 2 — tiefe Überzeugungen',dSub:'Klicke auf eine Formulierung, um sie in den Editor einzufügen.',search:'Überzeugungen durchsuchen…',empty:'Nichts gefunden'},
    it:{pTitle:'Convinzioni limitanti primarie',pSub:'Suggerimenti dal documento di origine. Fai clic su una formulazione per inserirla nell’editor.',dTitle:'Convinzione 2 — convinzioni profonde',dSub:'Fai clic su una formulazione per inserirla nell’editor.',search:'Cerca nelle convinzioni…',empty:'Nessun risultato'}
  };

  function lang(){const l=window.DiagnostikaI18n?.language||localStorage.getItem('diagnostika-ui-language')||'en';return PRIMARY[l]?l:'en';}
  function localizeDialog(dialog,type){
    if(!dialog)return;
    const l=lang(), u=UI[l], arr=type==='primary'?PRIMARY[l]:DEEP[l];
    const title=dialog.querySelector(type==='primary'?'.belief-hints-title':'.deep-belief-hints-title');
    const sub=dialog.querySelector(type==='primary'?'.belief-hints-sub':'.deep-belief-hints-sub');
    const search=dialog.querySelector(type==='primary'?'.belief-hints-search':'.deep-belief-hints-search');
    if(title)title.textContent=type==='primary'?u.pTitle:u.dTitle;
    if(sub)sub.textContent=type==='primary'?u.pSub:u.dSub;
    if(search)search.placeholder=u.search;
    const items=[...dialog.querySelectorAll(type==='primary'?'.belief-hint-item':'.deep-belief-hint-item')];
    items.forEach((item,i)=>{const text=item.lastElementChild;if(text&&arr[i])text.textContent=arr[i];item.dataset.localizedText=arr[i]||'';});
    const empty=dialog.querySelector(type==='primary'?'.belief-hints-empty':'.deep-belief-hints-empty');if(empty)empty.textContent=u.empty;
  }
  function localizeAll(){localizeDialog(document.querySelector('.belief-hints-dialog'),'primary');localizeDialog(document.querySelector('.deep-belief-hints-dialog'),'deep');}

  document.addEventListener('click',e=>{
    const item=e.target.closest?.('.belief-hint-item,.deep-belief-hint-item');
    if(!item)return;
    const text=item.dataset.localizedText;
    if(!text)return;
    e.preventDefault();e.stopImmediatePropagation();
    const editor=document.querySelector('#editorText');
    if(editor){editor.value=text;editor.focus();editor.setSelectionRange(text.length,text.length);}
    item.closest('dialog')?.close();
  },true);

  document.addEventListener('input',e=>{
    const input=e.target;
    const primary=input.matches?.('.belief-hints-search');
    const deep=input.matches?.('.deep-belief-hints-search');
    if(!primary&&!deep)return;
    e.stopImmediatePropagation();
    const dialog=input.closest('dialog'), type=primary?'primary':'deep', arr=type==='primary'?PRIMARY[lang()]:DEEP[lang()];
    const q=input.value.trim().toLowerCase();
    const items=[...dialog.querySelectorAll(type==='primary'?'.belief-hint-item':'.deep-belief-hint-item')];
    items.forEach((item,i)=>item.style.display=!q||String(arr[i]||'').toLowerCase().includes(q)?'':'none');
  },true);

  const observer=new MutationObserver(()=>localizeAll());
  observer.observe(document.body,{childList:true,subtree:true});
  const langBtnObserver=new MutationObserver(()=>localizeAll());
  const languageBtn=document.querySelector('.language-btn');if(languageBtn)langBtnObserver.observe(languageBtn,{childList:true,subtree:true,characterData:true});
  localizeAll();
})();